# Generated by Django 3.0.4 on 2020-03-29 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Advisory',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('version', models.BigIntegerField(default=0)),
                ('alias', models.CharField(max_length=255, unique=True)),
                ('created_by_cmsuser_id', models.BigIntegerField(blank=True, db_column='created_by_id', null=True)),
                ('date_created', models.DateTimeField()),
                ('description', models.TextField()),
                ('description_chinese', models.TextField(blank=True, null=True)),
                ('is_public', models.BooleanField()),
                ('last_updated', models.DateTimeField()),
                ('updated_by', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'advisory',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Instruction',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('version', models.BigIntegerField(default=0)),
                ('alias', models.CharField(max_length=255, unique=True)),
                ('created_by_cmsuser_id', models.BigIntegerField(blank=True, db_column='created_by_id', null=True)),
                ('date_created', models.DateTimeField()),
                ('description', models.TextField(blank=True, null=True)),
                ('description_chinese', models.TextField(blank=True, null=True)),
                ('is_public', models.BooleanField(default=True)),
                ('last_updated', models.DateTimeField()),
                ('updated_by', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'instruction',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SupplierManufacturer',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('version', models.BigIntegerField(default=0)),
                ('address', models.TextField(blank=True, null=True)),
                ('contact_person', models.CharField(blank=True, max_length=255, null=True)),
                ('date_created', models.DateTimeField()),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
                ('fax', models.CharField(blank=True, max_length=255, null=True)),
                ('last_updated', models.DateTimeField()),
                ('name', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('tel_home', models.CharField(blank=True, max_length=255, null=True)),
                ('tel_mobile', models.CharField(blank=True, max_length=255, null=True)),
                ('tel_office', models.CharField(blank=True, max_length=255, null=True)),
                ('supp_type', models.CharField(blank=True, choices=[('Certificate Holder', 'Certificate Holder'), ('Supplier', 'Supplier'), ('Manufacturer', 'Manufacturer')], db_column='type', max_length=255, null=True)),
                ('updated_by', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'supplier_manufacturer',
                'managed': False,
            },
        ),
    ]
