# Generated by Django 3.0.4 on 2020-04-18 18:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cmsinv', '0003_auto_20200402_1328'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='advisory',
            options={'managed': False, 'verbose_name_plural': 'Advisory list'},
        ),
        migrations.AlterModelOptions(
            name='delivery',
            options={'managed': False, 'verbose_name_plural': 'Deliveries'},
        ),
        migrations.AlterModelOptions(
            name='supplier',
            options={'managed': False, 'ordering': ['name']},
        ),
        migrations.CreateModel(
            name='InventoryItemSupplier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suppliers_idx', models.IntegerField(blank=True, default=0, null=True)),
                ('inventory_item', models.ForeignKey(db_column='inventory_item_suppliers_id', on_delete=django.db.models.deletion.PROTECT, to='cmsinv.InventoryItem')),
                ('supplier', models.ForeignKey(db_column='supplier_manufacturer_id', on_delete=django.db.models.deletion.PROTECT, to='cmsinv.Supplier')),
            ],
            options={
                'db_table': 'inventory_item_supplier_manufacturer',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='DepletionDepletionItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('items_idx', models.IntegerField(blank=True, null=True)),
                ('depletion', models.ForeignKey(db_column='depletion_items_id', on_delete=django.db.models.deletion.CASCADE, to='cmsinv.Depletion')),
                ('depletion_item', models.ForeignKey(db_column='depletion_item_id', on_delete=django.db.models.deletion.CASCADE, to='cmsinv.DepletionItem')),
            ],
            options={
                'db_table': 'depletion_depletion_item',
                'managed': True,
            },
        ),
    ]
