# Generated by Django 3.1.3 on 2021-01-02 07:59

import cmssys.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmsinv', '0004_auto_20200419_0247'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('version', models.BigIntegerField(default=0)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('encounter_id', models.BigIntegerField(blank=True, null=True)),
                ('language_id', models.BigIntegerField(blank=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('updated_by', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'prescription',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PrescriptionDetail',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('version', models.BigIntegerField(default=0)),
                ('dangerous_sign', cmssys.models.TextBooleanField()),
                ('dosage', models.CharField(max_length=255)),
                ('duration', models.CharField(max_length=255)),
                ('filled_in_clinic', cmssys.models.TextBooleanField()),
                ('frequency', models.CharField(max_length=255)),
                ('quantity', models.FloatField()),
                ('remark', models.TextField(blank=True, null=True)),
                ('status_print', models.IntegerField()),
                ('total_cost', models.FloatField()),
                ('unit', models.CharField(blank=True, max_length=255, null=True)),
                ('unit_price', models.FloatField()),
                ('details_idx', models.IntegerField(blank=True, null=True)),
                ('unit_drug_avg_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=19, null=True)),
            ],
            options={
                'db_table': 'prescription_detail',
                'managed': False,
            },
        ),
    ]
