# Generated by Django 3.1.3 on 2021-01-02 12:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cmsinv', '0005_prescription_prescriptiondetail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryitemsupplier',
            name='inventory_item',
            field=models.ForeignKey(db_column='inventory_item_suppliers_id', on_delete=django.db.models.deletion.CASCADE, to='cmsinv.inventoryitem'),
        ),
        migrations.AlterField(
            model_name='inventoryitemsupplier',
            name='supplier',
            field=models.ForeignKey(db_column='supplier_manufacturer_id', on_delete=django.db.models.deletion.CASCADE, to='cmsinv.supplier'),
        ),
    ]
