# Generated by Django 3.1.3 on 2021-02-04 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmsinv', '0006_auto_20210102_2001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='depletiondepletionitem',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='inventoryitemsupplier',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
