FROM python:3.7

# Set environment variables
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1
ENV HOME=/app
ENV APP_HOME=/app/backend

WORKDIR $APP_HOME
COPY requirements.txt $APP_HOME
RUN pip3 install --upgrade pip -r requirements.txt
COPY . $APP_HOME

CMD python3 manage.py collectstatic --noinput

