# Generated by Django 3.0.4 on 2020-04-18 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drugdb', '0002_auto_20200403_1554'),
    ]

    operations = [
        migrations.CreateModel(
            name='DrugUnit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='TAB', max_length=255)),
                ('description', models.CharField(default='Tablet', max_length=255)),
            ],
        ),
        migrations.AlterModelOptions(
            name='company',
            options={'ordering': ['name'], 'verbose_name_plural': 'Companies'},
        ),
        migrations.AlterModelOptions(
            name='registereddrug',
            options={'ordering': ['permit_no']},
        ),
    ]
