# Generated by Django 3.0.4 on 2020-04-18 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drugdb', '0003_auto_20200419_0247'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='drugunit',
            options={'ordering': ['name']},
        ),
    ]
