# Generated by Django 3.0.4 on 2020-04-19 21:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
        ('drugdb', '0005_auto_20200420_0533'),
    ]

    operations = [
        migrations.CreateModel(
            name='DrugDelivery',
            fields=[
                ('delivery_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='inventory.Delivery')),
                ('registration_no', models.CharField(blank=True, max_length=255, null=True)),
                ('items_unit', models.CharField(choices=[('AMPOULE', 'AMPOULE'), ('BOTTLE', 'BOTTLE'), ('BOX', 'BOX'), ('CAP', 'CAP'), ('DOSE', 'DOSE'), ('GRAM', 'GRAM'), ('INJECTION', 'INJECTION'), ('MG', 'MG'), ('ML', 'ML'), ('PACK', 'PACK'), ('TAB', 'TAB'), ('TUBE', 'TUBE'), ('UNIT', 'UNIT'), ('VIAL', 'VIAL')], default='TAB', max_length=100)),
            ],
            bases=('inventory.delivery',),
        ),
    ]
