# Generated by Django 3.0.5 on 2020-04-28 00:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drugdb', '0008_auto_20200426_0715'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='drugdelivery',
            options={'verbose_name': 'Drug delivery', 'verbose_name_plural': 'Drug deliveries'},
        ),
        migrations.AlterModelOptions(
            name='registereddrug',
            options={'ordering': ['reg_no'], 'verbose_name': 'Registered drug'},
        ),
    ]
