# Generated by Django 3.0.5 on 2020-05-05 18:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cmsinv', '0004_auto_20200419_0247'),
        ('drugdb', '0009_auto_20200428_0854'),
    ]

    operations = [
        migrations.AddField(
            model_name='drugdelivery',
            name='cms_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cmsinv.InventoryItem'),
        ),
    ]
