# Generated by Django 3.0.5 on 2020-05-05 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drugdb', '0010_drugdelivery_cms_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='drugdelivery',
            old_name='cms_id',
            new_name='cms_item',
        ),
    ]
