# Generated by Django 3.0.5 on 2020-05-05 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drugdb', '0011_auto_20200506_0254'),
    ]

    operations = [
        migrations.RenameField(
            model_name='drugdelivery',
            old_name='cms_item',
            new_name='cmsinv_item',
        ),
    ]
