# Generated by Django 3.0.5 on 2020-05-24 08:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0005_auto_20200516_1606'),
        ('drugdb', '0012_auto_20200506_0255'),
    ]

    operations = [
        migrations.AddField(
            model_name='drugdelivery',
            name='bill',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='ledger.Expense'),
        ),
    ]
