# Generated by Django 3.1.2 on 2020-10-29 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drugdb', '0013_drugdelivery_bill'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registereddrug',
            old_name='ingredients',
            new_name='ingredient_list',
        ),
        migrations.AddField(
            model_name='company',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='registereddrug',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
