# Generated by Django 3.1.2 on 2020-10-29 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drugdb', '0015_auto_20201029_1812'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registereddrug',
            old_name='ingredient_list',
            new_name='ingredients_str',
        ),
    ]
