# Generated by Django 3.1.3 on 2020-11-13 06:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cmsinv', '0004_auto_20200419_0247'),
        ('drugdb', '0016_auto_20201030_0409'),
    ]

    operations = [
        migrations.AddField(
            model_name='registereddrug',
            name='cmsinv_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cmsinv.inventoryitem'),
        ),
    ]
