# Generated by Django 3.1.3 on 2020-11-14 04:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drugdb', '0017_registereddrug_cmsinv_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registereddrug',
            name='cmsinv_item',
        ),
    ]
