# Generated by Django 3.1.3 on 2021-01-02 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drugdb', '0018_remove_registereddrug_cmsinv_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='registereddrug',
            name='itemid',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True),
        ),
    ]
