# Generated by Django 3.1.3 on 2021-01-02 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drugdb', '0020_auto_20210102_1949'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DrugDelivery',
        ),
    ]
