# Generated by Django 3.1.3 on 2021-01-09 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drugdb', '0021_delete_drugdelivery'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registereddrug',
            name='ingredients_str',
        ),
        migrations.AddField(
            model_name='registereddrug',
            name='last_synced',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
