# Generated by Django 3.0.4 on 2020-04-19 21:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255)),
                ('vendor', models.CharField(blank=True, max_length=255, null=True)),
                ('delivery_note_no', models.CharField(blank=True, max_length=255, null=True)),
                ('purchase_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('purchase_unit', models.CharField(choices=[('PACK', 'Pack'), ('BOX', 'Box')], default='PACK', max_length=100)),
                ('bonus_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('items_per_purchase', models.DecimalField(decimal_places=2, default=1, max_digits=10)),
                ('batch_num', models.CharField(blank=True, max_length=100, null=True)),
                ('other_ref', models.CharField(blank=True, max_length=100, null=True)),
                ('remark', models.CharField(blank=True, max_length=255, null=True)),
                ('delivery_date', models.DateField(auto_now_add=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='ConsumableDelivery',
            fields=[
                ('delivery_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='inventory.Delivery')),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('category', models.CharField(default='MED', max_length=255)),
                ('items_unit', models.CharField(choices=[('PC', 'Piece')], default='PC', max_length=100)),
            ],
            bases=('inventory.delivery',),
        ),
    ]
