# Generated by Django 3.0.4 on 2020-04-23 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_auto_20200422_2308'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vendor',
            old_name='tel_home',
            new_name='tel_main',
        ),
    ]
