# Generated by Django 3.0.4 on 2020-04-25 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_auto_20200423_2027'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='value',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='is_active',
            new_name='active',
        ),
        migrations.RenameField(
            model_name='itemtype',
            old_name='value',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='vendor',
            old_name='is_active',
            new_name='active',
        ),
    ]
