# Generated by Django 3.0.4 on 2020-04-25 22:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_vendor_remarks'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vendor',
            old_name='date_modified',
            new_name='last_updated',
        ),
    ]
