# Generated by Django 3.0.5 on 2020-04-28 00:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_auto_20200426_1022'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itemdelivery',
            options={'ordering': ['received_date'], 'verbose_name': 'Item delivery', 'verbose_name_plural': 'Item deliveries'},
        ),
        migrations.AlterModelOptions(
            name='itemtype',
            options={'ordering': ['id'], 'verbose_name': 'Item type'},
        ),
    ]
