# Generated by Django 3.0.5 on 2020-04-28 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_auto_20200428_0854'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='discontinue',
        ),
        migrations.RemoveField(
            model_name='itemtype',
            name='version',
        ),
        migrations.AddField(
            model_name='delivery',
            name='version',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='category',
            name='version',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='item',
            name='version',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='version',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
