# Generated by Django 3.0.5 on 2020-05-25 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0012_auto_20200428_0904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='received_date',
            field=models.DateField(),
        ),
    ]
