# Generated by Django 3.1.2 on 2020-10-25 02:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0013_auto_20200525_1905'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='default_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventory.category'),
        ),
        migrations.AddField(
            model_name='vendor',
            name='default_description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
