# Generated by Django 3.1.2 on 2020-10-26 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0016_auto_20201025_1036'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='expiry_month',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
    ]
