# Generated by Django 3.1.2 on 2020-10-26 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0017_delivery_expiry_month'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='expiry_month',
            field=models.CharField(blank=True, default='', max_length=8, null=True),
        ),
    ]
