# Generated by Django 3.1.2 on 2020-10-30 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0018_auto_20201026_1206'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='alias',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
