# Generated by Django 3.1.2 on 2020-10-31 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0019_vendor_alias'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='is_supplier',
            field=models.BooleanField(default=False),
        ),
    ]
