# Generated by Django 3.1.2 on 2020-10-31 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0020_vendor_is_supplier'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vendor',
            options={'ordering': ['name'], 'permissions': (('can_view_supplier', 'Can view supplier'), ('can_change_supplier', 'Can change supplier'))},
        ),
    ]
