# Generated by Django 3.1.2 on 2020-11-03 02:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('drugdb', '0016_auto_20201030_0409'),
        ('ledger', '0006_auto_20201025_0930'),
        ('inventory', '0021_auto_20201031_1841'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_quantity', models.DecimalField(decimal_places=1, default=0, max_digits=10)),
                ('purchase_unit', models.CharField(choices=[('PACK', 'Pack'), ('BOX', 'Box')], default='PACK', max_length=100)),
                ('bonus_quantity', models.DecimalField(decimal_places=1, default=0, max_digits=10)),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('discount', models.DecimalField(decimal_places=0, default=0, max_digits=4)),
                ('items_per_purchase', models.DecimalField(decimal_places=2, default=1, max_digits=10)),
                ('batch_num', models.CharField(blank=True, max_length=100, null=True)),
                ('other_ref', models.CharField(blank=True, max_length=100, null=True)),
                ('expiry_month', models.CharField(blank=True, default='', max_length=8, null=True, verbose_name='Expiry (YYYYMM)')),
                ('version', models.PositiveIntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='DeliveryOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_no', models.CharField(blank=True, max_length=255, null=True)),
                ('invoice_date', models.DateField(blank=True, null=True)),
                ('received_date', models.DateField(blank=True, null=True)),
                ('received_by', models.CharField(blank=True, max_length=255, null=True)),
                ('payee', models.CharField(blank=True, max_length=255, null=True)),
                ('payment_ref', models.CharField(blank=True, max_length=255, null=True, verbose_name='Cheque/ref no.')),
                ('expected_date', models.DateField(blank=True, null=True, verbose_name='Cheque/paid date')),
                ('other_ref', models.CharField(blank=True, max_length=255, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('updated_by', models.CharField(blank=True, max_length=255, null=True)),
                ('version', models.PositiveIntegerField(default=1)),
            ],
            options={
                'ordering': ['-invoice_date'],
            },
        ),
        migrations.RemoveField(
            model_name='item',
            name='inventory_type',
        ),
        migrations.RemoveField(
            model_name='item',
            name='vendor',
        ),
        migrations.AddField(
            model_name='item',
            name='clinic_no',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='dangerous_drug',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='item_type',
            field=models.CharField(choices=[('DRUG', 'Drug'), ('CONS', 'Consumable'), ('MISC', 'Other')], default='DRUG', max_length=4),
        ),
        migrations.AddField(
            model_name='item',
            name='item_unit',
            field=models.CharField(choices=[('AMPOULE', 'Ampoule'), ('BOTTLE', 'Bottle'), ('BOX', 'Box'), ('CAP', 'Cap'), ('DOSE', 'Dose'), ('GRAM', 'gram'), ('INJECTION', 'Injection'), ('MG', 'mg'), ('ML', 'mL'), ('PACK', 'Pack'), ('TAB', 'Tablet'), ('TUBE', 'Tube'), ('UNIT', 'Unit'), ('VIAL', 'Vial')], default='TAB', max_length=100),
        ),
        migrations.AddField(
            model_name='item',
            name='label',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='reg_drug',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='drugdb.registereddrug'),
        ),
        migrations.DeleteModel(
            name='ItemDelivery',
        ),
        migrations.AddField(
            model_name='deliveryorder',
            name='delivery_items',
            field=models.ManyToManyField(through='inventory.DeliveryItems', to='inventory.Item'),
        ),
        migrations.AddField(
            model_name='deliveryorder',
            name='payment_method',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ledger.paymentmethod'),
        ),
        migrations.AddField(
            model_name='deliveryorder',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventory.vendor'),
        ),
        migrations.AddField(
            model_name='deliveryitems',
            name='delivery_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.deliveryorder'),
        ),
        migrations.AddField(
            model_name='deliveryitems',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.item'),
        ),
    ]
