# Generated by Django 3.1.2 on 2020-11-03 02:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0006_auto_20201025_0930'),
        ('inventory', '0022_auto_20201103_1029'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryorder',
            name='bill',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='ledger.expense'),
        ),
        migrations.AddField(
            model_name='deliveryorder',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
    ]
