# Generated by Django 3.1.2 on 2020-11-03 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0023_auto_20201103_1052'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryorder',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
