# Generated by Django 3.1.2 on 2020-11-04 04:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0026_auto_20201103_1327'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_quantity', models.DecimalField(decimal_places=1, default=0, max_digits=10)),
                ('purchase_unit', models.CharField(choices=[('PACK', 'Pack'), ('BOX', 'Box')], default='PACK', max_length=100)),
                ('bonus_quantity', models.DecimalField(decimal_places=1, default=0, max_digits=10)),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('discount', models.DecimalField(decimal_places=0, default=0, max_digits=4)),
                ('items_per_purchase', models.DecimalField(decimal_places=2, default=1, max_digits=10)),
                ('batch_num', models.CharField(blank=True, max_length=100, null=True)),
                ('other_ref', models.CharField(blank=True, max_length=100, null=True)),
                ('expiry_month', models.CharField(blank=True, default='', max_length=8, null=True, verbose_name='Expiry (YYYYMM)')),
                ('version', models.PositiveIntegerField(default=1)),
            ],
        ),
        migrations.RemoveField(
            model_name='deliveryorder',
            name='delivery_items',
        ),
        migrations.DeleteModel(
            name='DeliveryItems',
        ),
        migrations.AddField(
            model_name='deliveryitem',
            name='delivery_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_items', to='inventory.deliveryorder'),
        ),
        migrations.AddField(
            model_name='deliveryitem',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_items', to='inventory.item'),
        ),
        migrations.AddField(
            model_name='deliveryorder',
            name='items',
            field=models.ManyToManyField(blank=True, through='inventory.DeliveryItem', to='inventory.Item'),
        ),
    ]
