# Generated by Django 3.1.2 on 2020-11-04 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0027_auto_20201104_1249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryorder',
            name='items',
            field=models.ManyToManyField(blank=True, related_name='delivery_orders', through='inventory.DeliveryItem', to='inventory.Item'),
        ),
        migrations.AlterField(
            model_name='item',
            name='dangerous_drug',
            field=models.BooleanField(default=False),
        ),
    ]
