# Generated by Django 3.1.2 on 2020-11-05 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0028_auto_20201105_0330'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='generic_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
