# Generated by Django 3.1.2 on 2020-11-05 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0029_item_generic_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryitem',
            name='is_sample',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='deliveryitem',
            name='items_per_purchase',
            field=models.DecimalField(decimal_places=0, default=1, max_digits=10),
        ),
    ]
