# Generated by Django 3.1.2 on 2020-11-05 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0030_auto_20201105_1639'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='reg_drug',
        ),
        migrations.AddField(
            model_name='item',
            name='permit_no',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
