# Generated by Django 3.1.2 on 2020-11-05 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0031_auto_20201105_1813'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='permit_no',
            new_name='reg_no',
        ),
    ]
