# Generated by Django 3.1.3 on 2020-11-13 05:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cmsinv', '0004_auto_20200419_0247'),
        ('inventory', '0033_auto_20201111_0305'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='version',
        ),
        migrations.RemoveField(
            model_name='item',
            name='alias',
        ),
        migrations.RemoveField(
            model_name='item',
            name='clinic_no',
        ),
        migrations.RemoveField(
            model_name='item',
            name='dangerous_drug',
        ),
        migrations.RemoveField(
            model_name='item',
            name='description',
        ),
        migrations.RemoveField(
            model_name='item',
            name='generic_name',
        ),
        migrations.RemoveField(
            model_name='item',
            name='label',
        ),
        migrations.RemoveField(
            model_name='item',
            name='reg_no',
        ),
        migrations.RemoveField(
            model_name='item',
            name='remarks',
        ),
        migrations.AddField(
            model_name='category',
            name='value',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='item',
            name='cms',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cmsinv.inventoryitem'),
        ),
        migrations.AddField(
            model_name='itemtype',
            name='value',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventory.itemtype'),
        ),
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
