# Generated by Django 3.1.3 on 2020-11-13 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0034_auto_20201113_1323'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['value'], 'verbose_name_plural': 'Categories'},
        ),
    ]
