# Generated by Django 3.1.3 on 2020-11-14 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0035_auto_20201113_1421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryitem',
            name='purchase_unit',
            field=models.CharField(choices=[('PACK', 'Pack'), ('BOX', 'Box')], default='BOX', max_length=100),
        ),
    ]
