# Generated by Django 3.1.3 on 2020-11-14 02:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cmsinv', '0004_auto_20200419_0247'),
        ('inventory', '0036_auto_20201114_0959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryitem',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_items', to='cmsinv.inventoryitem'),
        ),
        migrations.AlterField(
            model_name='deliveryorder',
            name='items',
            field=models.ManyToManyField(blank=True, related_name='delivery_orders', through='inventory.DeliveryItem', to='cmsinv.InventoryItem'),
        ),
    ]
