# Generated by Django 3.1.3 on 2020-11-14 02:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0038_auto_20201114_1033'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='active',
            new_name='is_active',
        ),
    ]
