# Generated by Django 3.1.3 on 2020-11-14 03:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0040_auto_20201114_1106'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='cms',
            new_name='cmsid',
        ),
    ]
