# Generated by Django 3.1.3 on 2020-11-14 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0042_item_reg_drug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='item_unit',
        ),
        migrations.AddField(
            model_name='item',
            name='note',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
