# Generated by Django 3.1.3 on 2020-11-14 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0043_auto_20201114_1256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemtype',
            name='value',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
