# Generated by Django 3.1.3 on 2020-11-14 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0044_auto_20201114_1310'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='reg_drug',
        ),
        migrations.AddField(
            model_name='item',
            name='reg_no',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
