# Generated by Django 3.1.3 on 2020-11-16 02:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cmsinv', '0004_auto_20200419_0247'),
        ('inventory', '0045_auto_20201114_1350'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='cmsinv_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cmsinv.inventoryitem'),
        ),
    ]
