# Generated by Django 3.1.3 on 2020-11-16 02:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0046_item_cmsinv_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='cmsinv_item',
        ),
    ]
