# Generated by Django 3.1.3 on 2020-11-16 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0047_remove_item_cmsinv_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliveryorder',
            name='expected_date',
        ),
        migrations.RemoveField(
            model_name='deliveryorder',
            name='payee',
        ),
        migrations.RemoveField(
            model_name='deliveryorder',
            name='payment_method',
        ),
        migrations.RemoveField(
            model_name='deliveryorder',
            name='payment_ref',
        ),
        migrations.AddField(
            model_name='deliveryorder',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
