# Generated by Django 3.1.3 on 2020-11-26 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0048_auto_20201116_1141'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryitem',
            name='items_unit',
            field=models.CharField(blank=True, choices=[('AMPOULE', 'Ampoule'), ('BOTTLE', 'Bottle'), ('BOX', 'Box'), ('CAP', 'Cap'), ('DOSE', 'Dose'), ('GRAM', 'gram'), ('INJECTION', 'Injection'), ('MG', 'mg'), ('ML', 'mL'), ('PACK', 'Pack'), ('TAB', 'Tablet'), ('TUBE', 'Tube'), ('UNIT', 'Unit'), ('VIAL', 'Vial')], max_length=10, null=True),
        ),
    ]
