# Generated by Django 3.1.3 on 2020-12-22 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0049_deliveryitem_items_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryorder',
            name='cms_delivery_id',
            field=models.BigIntegerField(blank=True, default=None, null=True),
        ),
    ]
