# Generated by Django 3.1.3 on 2020-12-27 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0050_deliveryorder_cms_delivery_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryorder',
            name='cms_synced',
            field=models.BooleanField(default=False),
        ),
    ]
