# Generated by Django 3.1.3 on 2020-12-31 23:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0051_deliveryorder_cms_synced'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventory.vendor'),
        ),
    ]
