# Generated by Django 3.1.3 on 2021-01-09 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0053_auto_20210105_1025'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Delivery',
        ),
    ]
