# Generated by Django 3.1.3 on 2021-01-02 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0053_auto_20210101_0824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='cmsid',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='reg_no',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
