# Generated by Django 3.1.3 on 2021-01-13 08:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0009_incomecategory_incomesource'),
        ('inventory', '0054_delete_delivery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='default_exp_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='ledger.expensecategory', verbose_name='Expense category'),
        ),
    ]
