# Generated by Django 3.1.3 on 2021-01-16 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0055_auto_20210113_1658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryitem',
            name='bonus_quantity',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='deliveryitem',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4),
        ),
        migrations.AlterField(
            model_name='deliveryitem',
            name='purchase_quantity',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
