# Generated by Django 3.1.3 on 2021-01-28 02:40

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0056_auto_20210116_1836'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryorder',
            name='vendor',
            field=models.ForeignKey(default=211, on_delete=django.db.models.deletion.PROTECT, to='inventory.vendor'),
            preserve_default=False,
        ),
    ]
