# Generated by Django 3.0.4 on 2020-04-18 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cmssys', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='auditlog',
            options={'managed': False, 'ordering': ['-last_updated']},
        ),
        migrations.AlterModelOptions(
            name='cmsuser',
            options={'managed': False, 'ordering': ['id']},
        ),
    ]
