# Generated by Django 3.1.2 on 2020-10-28 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmssys', '0002_auto_20200419_0247'),
    ]

    operations = [
        migrations.CreateModel(
            name='Encounter',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('version', models.BigIntegerField()),
                ('consultation_notes_id', models.BigIntegerField(blank=True, null=True)),
                ('date_created', models.DateTimeField()),
                ('last_updated', models.DateTimeField()),
                ('patient_id', models.BigIntegerField()),
                ('prescription_id', models.BigIntegerField(blank=True, null=True)),
                ('vital_sign_id', models.BigIntegerField(blank=True, null=True)),
                ('consumable_id', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'encounter',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EncounterType',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('version', models.BigIntegerField()),
                ('label', models.CharField(max_length=255)),
                ('value', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'encounter_type',
                'managed': False,
            },
        ),
    ]
