# Generated by Django 3.1.3 on 2021-01-25 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmssys', '0003_encounter_encountertype'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('version', models.BigIntegerField()),
                ('active', models.TextField()),
                ('address_id', models.BigIntegerField(blank=True, null=True)),
                ('alias1', models.CharField(blank=True, max_length=255, null=True)),
                ('alias2', models.CharField(blank=True, max_length=255, null=True)),
                ('chinese_given_name', models.CharField(blank=True, max_length=255, null=True)),
                ('chinese_sur_name', models.CharField(blank=True, max_length=255, null=True)),
                ('date_created', models.DateTimeField()),
                ('dob', models.DateTimeField(blank=True, null=True)),
                ('dob_inexact', models.TextField()),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
                ('epr', models.TextField()),
                ('fax', models.CharField(blank=True, max_length=255, null=True)),
                ('given_name', models.CharField(blank=True, max_length=255, null=True)),
                ('language_id', models.BigIntegerField(blank=True, null=True)),
                ('last_updated', models.DateTimeField()),
                ('medical_background_id', models.BigIntegerField(blank=True, null=True)),
                ('memo', models.TextField(blank=True, null=True)),
                ('nextofkin1_id', models.BigIntegerField(blank=True, null=True)),
                ('nextofkin2_id', models.BigIntegerField(blank=True, null=True)),
                ('official_id', models.CharField(blank=True, max_length=255, null=True)),
                ('official_id_type_id', models.BigIntegerField()),
                ('pager', models.CharField(blank=True, max_length=255, null=True)),
                ('patient_no', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('referrer_id', models.BigIntegerField(blank=True, null=True)),
                ('register_clinic', models.CharField(blank=True, max_length=255, null=True)),
                ('responsible_doctor_id', models.BigIntegerField(blank=True, null=True)),
                ('security', models.TextField()),
                ('sex_id', models.BigIntegerField(blank=True, null=True)),
                ('special_instructions', models.TextField(blank=True, null=True)),
                ('sur_name', models.CharField(blank=True, max_length=255, null=True)),
                ('tel_home', models.CharField(blank=True, max_length=255, null=True)),
                ('tel_mobile', models.CharField(blank=True, max_length=255, null=True)),
                ('tel_office', models.CharField(blank=True, max_length=255, null=True)),
                ('updated_by', models.CharField(blank=True, max_length=255, null=True)),
                ('address_work_id', models.BigIntegerField(blank=True, null=True)),
                ('doi', models.DateTimeField(blank=True, null=True)),
                ('patient_address', models.CharField(blank=True, max_length=255, null=True)),
                ('patient_type_id', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'patient',
                'managed': False,
            },
        ),
    ]
