# Generated by Django 3.0.5 on 2020-04-28 00:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LedgerEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_date', models.DateField(auto_now_add=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('expected_date', models.DateField(blank=True, null=True)),
                ('settled_date', models.DateField(blank=True, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('updated_by', models.CharField(blank=True, max_length=255, null=True)),
                ('version', models.PositiveIntegerField(default=1)),
            ],
            options={
                'verbose_name': 'Ledger entry',
                'verbose_name_plural': 'Ledger entries',
                'ordering': ['-entry_date'],
            },
        ),
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Payment method',
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='expensecategory',
            options={'ordering': ['name'], 'verbose_name': 'Expense category', 'verbose_name_plural': 'Expense categories'},
        ),
        migrations.AddField(
            model_name='expensecategory',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('ledgerentry_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ledger.LedgerEntry')),
                ('payee', models.CharField(blank=True, max_length=255, null=True)),
                ('payment_ref', models.CharField(blank=True, max_length=255, null=True)),
                ('invoice_no', models.CharField(blank=True, max_length=255, null=True)),
                ('invoice_date', models.DateField(blank=True, null=True)),
                ('other_ref', models.CharField(blank=True, max_length=255, null=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='ledger.ExpenseCategory')),
                ('payment_method', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ledger.PaymentMethod')),
            ],
            options={
                'verbose_name': 'Expense',
                'verbose_name_plural': 'Expenses',
                'ordering': ['-entry_date'],
            },
            bases=('ledger.ledgerentry',),
        ),
    ]
