# Generated by Django 3.0.5 on 2020-04-28 07:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0012_auto_20200428_0904'),
        ('ledger', '0002_auto_20200428_0837'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventory.Vendor'),
        ),
        migrations.AlterField(
            model_name='ledgerentry',
            name='entry_date',
            field=models.DateField(),
        ),
    ]
