# Generated by Django 3.0.5 on 2020-05-07 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0003_auto_20200428_1559'),
    ]

    operations = [
        migrations.AddField(
            model_name='expensecategory',
            name='label',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
