# Generated by Django 3.0.5 on 2020-05-16 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0004_expensecategory_label'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='expensecategory',
            options={'ordering': ['label', '-active'], 'verbose_name': 'Expense category', 'verbose_name_plural': 'Expense categories'},
        ),
        migrations.AlterField(
            model_name='expensecategory',
            name='label',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
