# Generated by Django 3.1.3 on 2020-11-12 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0006_auto_20201025_0930'),
    ]

    operations = [
        migrations.AddField(
            model_name='expensecategory',
            name='code',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
