# Generated by Django 3.1.3 on 2021-01-13 09:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0009_incomecategory_incomesource'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='incomecategory',
            options={'ordering': ['code', '-active'], 'verbose_name': 'Income category', 'verbose_name_plural': 'Income categories'},
        ),
        migrations.AddField(
            model_name='incomesource',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='ledger.incomecategory'),
        ),
    ]
