# Generated by Django 3.1.3 on 2021-01-14 03:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0010_auto_20210113_1706'),
    ]

    operations = [
        migrations.CreateModel(
            name='Income',
            fields=[
                ('ledgerentry_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ledger.ledgerentry')),
                ('payment_ref', models.CharField(blank=True, max_length=255, null=True, verbose_name='Cheque/ref no.')),
                ('invoice_no', models.CharField(blank=True, max_length=255, null=True)),
                ('invoice_date', models.DateField(blank=True, null=True)),
                ('other_ref', models.CharField(blank=True, max_length=255, null=True)),
                ('payer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ledger.incomesource')),
                ('payment_method', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ledger.paymentmethod')),
            ],
            options={
                'verbose_name': 'Income',
                'ordering': ['-entry_date'],
            },
            bases=('ledger.ledgerentry',),
        ),
    ]
