# Generated by Django 3.1.3 on 2021-01-15 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0011_income'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incomesource',
            name='account_no',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
