# Generated by Django 3.1.3 on 2021-01-22 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0012_auto_20210115_2230'),
    ]

    operations = [
        migrations.AddField(
            model_name='ledgerentry',
            name='permanent',
            field=models.BooleanField(default=False),
        ),
    ]
