# Generated by Django 3.1.3 on 2021-01-22 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0013_ledgerentry_permanent'),
    ]

    operations = [
        migrations.AddField(
            model_name='ledgerentry',
            name='trashed',
            field=models.BooleanField(default=False),
        ),
    ]
