# Generated by Django 3.0.4 on 2020-04-18 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('version', models.BigIntegerField(default=1)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('encounter_id', models.BigIntegerField(blank=True, null=True)),
                ('invoice_print_status', models.BooleanField(default=False)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('receipt_print_status', models.BooleanField(default=False)),
                ('total', models.FloatField()),
                ('updated_by', models.CharField(blank=True, max_length=255, null=True)),
                ('transaction_code', models.CharField(blank=True, max_length=255, null=True)),
                ('unbalance_amt', models.FloatField(default=0)),
                ('daily_sequence_per_clinic', models.IntegerField(blank=True, null=True)),
                ('payment_update_count', models.IntegerField(blank=True, null=True)),
                ('temp_wq_arrive_time', models.DateTimeField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'bill',
                'ordering': ['-date_created'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BillDetail',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('version', models.BigIntegerField(default=0)),
                ('billed_amount', models.FloatField()),
                ('remarks', models.TextField(blank=True, null=True)),
                ('standard', models.FloatField()),
                ('bill_details_idx', models.IntegerField(blank=True, null=True)),
                ('discount_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=19, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('quantity', models.DecimalField(blank=True, decimal_places=2, max_digits=19, null=True)),
            ],
            options={
                'db_table': 'bill_detail',
                'ordering': ['-id'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Cashbook',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('version', models.BigIntegerField(default=0)),
                ('amount', models.FloatField()),
                ('date_created', models.DateField(auto_now_add=True)),
                ('editable', models.BooleanField(default=False)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('reference_id', models.CharField(blank=True, max_length=255, null=True)),
                ('remark', models.TextField(blank=True, choices=[('Delivery', 'Delivery'), ('Dispensary', 'Dispensary')], null=True)),
                ('entry_type', models.CharField(blank=True, choices=[('bill', 'Bill'), ('Delivery', 'Delivery')], db_column='type', max_length=255, null=True)),
                ('updated_by', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name_plural': 'Cashbook',
                'db_table': 'cashbook',
                'ordering': ['-id'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ChargeItem',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('version', models.BigIntegerField(default=0)),
                ('alias', models.CharField(max_length=255)),
                ('cp_prescription_amt', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True, null=True)),
                ('description_chinese', models.TextField(blank=True, null=True)),
                ('is_default', models.BooleanField(default=False)),
                ('is_public', models.BooleanField(default=True)),
                ('owner_id', models.BigIntegerField(blank=True, null=True)),
                ('standard_amount', models.FloatField()),
                ('cp_consumable_amt', models.BooleanField(default=False)),
                ('inactive', models.BooleanField(default=False)),
                ('sys_is_deleted', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'charge_item',
                'ordering': ['alias'],
                'managed': False,
            },
        ),
    ]
