# Generated by Django 3.1.3 on 2021-01-27 03:16

import cmssys.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmsacc', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentDetails',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('version', models.BigIntegerField()),
                ('amount', models.FloatField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('remark', models.TextField(blank=True, null=True)),
                ('status_print', models.IntegerField()),
                ('updated_by', models.CharField(blank=True, max_length=255, null=True)),
                ('clear_payment', cmssys.models.TextBooleanField()),
                ('paid_amt', models.FloatField(blank=True, null=True)),
                ('payment_date', models.DateTimeField(blank=True, null=True)),
                ('receive_date', models.DateTimeField(blank=True, null=True)),
                ('receive_method_id', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'payment_details',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('version', models.BigIntegerField()),
                ('payment_method', models.CharField(max_length=255)),
                ('payment_method_chinese', models.CharField(max_length=255)),
                ('acc_receivable_fg', cmssys.models.TextBooleanField()),
                ('reference', models.CharField(blank=True, max_length=255, null=True)),
                ('active', cmssys.models.TextBooleanField()),
            ],
            options={
                'db_table': 'payment_method',
                'managed': False,
            },
        ),
    ]
