# Generated by Django 3.1.3 on 2021-02-04 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cmsacc', '0002_paymentdetails_paymentmethod'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bill',
            options={'managed': False, 'ordering': ['-last_updated']},
        ),
    ]
